import React, { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import {
    Plus,
    X,
    Upload,
    Image as ImageIcon,
    ChefHat,
    FileText,
    Layers,
    Save,
    ArrowLeft
} from 'lucide-react';

/**
 * PURPOSE: Allow users to create custom recipes.
 * WHY: Provides a manual entry option for recipes not generated by AI.
 * IMPACT: Increases user engagement and content diversity.
 */
const CreateRecipe = () => {
    const navigate = useNavigate();
    const [loading, setLoading] = useState(false);
    const [title, setTitle] = useState('');
    const [ingredients, setIngredients] = useState(['']);
    const [instructions, setInstructions] = useState(['']);
    const [image, setImage] = useState(null);
    const [imagePreview, setImagePreview] = useState(null);
    const [isPublic, setIsPublic] = useState(false);

    // PURPOSE: Add a new empty ingredient field.
    const addIngredient = () => setIngredients([...ingredients, '']);

    // PURPOSE: Remove a specific ingredient field.
    const removeIngredient = (index) => {
        const newIngs = ingredients.filter((_, i) => i !== index);
        setIngredients(newIngs.length ? newIngs : ['']);
    };

    // PURPOSE: Update the value of a specific ingredient field.
    const updateIngredient = (index, value) => {
        const newIngs = [...ingredients];
        newIngs[index] = value;
        setIngredients(newIngs);
    };

    // PURPOSE: Add a new empty instruction step.
    const addInstruction = () => setInstructions([...instructions, '']);

    // PURPOSE: Remove a specific instruction step.
    const removeInstruction = (index) => {
        const newSteps = instructions.filter((_, i) => i !== index);
        setInstructions(newSteps.length ? newSteps : ['']);
    };

    // PURPOSE: Update the value of a specific instruction step.
    const updateInstruction = (index, value) => {
        const newSteps = [...instructions];
        newSteps[index] = value;
        setInstructions(newSteps);
    };

    // PURPOSE: Handle image selection and preview generation.
    const handleImageChange = (e) => {
        const file = e.target.files[0];
        if (file) {
            setImage(file);
            const reader = new FileReader();
            reader.onloadend = () => {
                setImagePreview(reader.result);
            };
            reader.readAsDataURL(file);
        }
    };

    // PURPOSE: Submit the recipe to the backend.
    const handleSubmit = async (e) => {
        e.preventDefault();

        // Basic Validation
        if (!title.trim()) {
            toast.error('Recipe title is required');
            return;
        }

        const filteredIngredients = ingredients.filter(i => i.trim() !== '');
        if (filteredIngredients.length === 0) {
            toast.error('At least one ingredient is required');
            return;
        }

        const filteredInstructions = instructions.filter(i => i.trim() !== '');

        setLoading(true);
        const token = localStorage.getItem('token');

        const formData = new FormData();
        formData.append('title', title);
        formData.append('ingredients', JSON.stringify(filteredIngredients));
        formData.append('instructions', JSON.stringify(filteredInstructions));
        formData.append('is_public', isPublic);
        if (image) {
            formData.append('image', image);
        }

        try {
            await axios.post('http://127.0.0.1:5000/api/recipes/create', formData, {
                headers: {
                    'Authorization': `Bearer ${token}`,
                    'Content-Type': 'multipart/form-data'
                }
            });
            toast.success('Recipe created successfully!');
            navigate('/dashboard');
        } catch (err) {
            toast.error(err.response?.data?.error || 'Failed to create recipe');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="max-w-4xl mx-auto px-4 py-12">
            <button
                onClick={() => navigate(-1)}
                className="flex items-center gap-2 text-gray-600 dark:text-gray-400 hover:text-orange-500 mb-8 transition-colors"
            >
                <ArrowLeft size={20} />
                Back
            </button>

            <div className="bg-white dark:bg-gray-800 rounded-3xl shadow-xl overflow-hidden border border-gray-100 dark:border-gray-700">
                <div className="bg-gradient-to-r from-orange-500 to-red-600 p-8 text-white">
                    <h1 className="text-3xl font-bold flex items-center gap-3">
                        <ChefHat size={32} />
                        Create Your Own Recipe
                    </h1>
                    <p className="mt-2 text-orange-50 opacity-90">Share your culinary secrets with the community.</p>
                </div>

                <form onSubmit={handleSubmit} className="p-8 space-y-8">
                    {/* Basic Info */}
                    <div className="space-y-4">
                        <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 uppercase tracking-wider">
                            Recipe Title
                        </label>
                        <input
                            type="text"
                            value={title}
                            onChange={(e) => setTitle(e.target.value)}
                            placeholder="e.g. Grandma's Secret Pasta Sauce"
                            className="w-full px-6 py-4 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-2xl focus:ring-2 focus:ring-orange-500 outline-none transition-all dark:text-white"
                        />
                    </div>

                    {/* Image Upload */}
                    <div className="space-y-4">
                        <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 uppercase tracking-wider">
                            Recipe Photo
                        </label>
                        <div className="relative group">
                            {imagePreview ? (
                                <div className="relative rounded-2xl overflow-hidden h-64 border-2 border-dashed border-gray-300 dark:border-gray-600">
                                    <img src={imagePreview} alt="Preview" className="w-full h-full object-cover" />
                                    <button
                                        type="button"
                                        onClick={() => { setImage(null); setImagePreview(null); }}
                                        className="absolute top-4 right-4 p-2 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors shadow-lg"
                                    >
                                        <X size={20} />
                                    </button>
                                </div>
                            ) : (
                                <label className="flex flex-col items-center justify-center h-64 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-2xl cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-900 transition-all group">
                                    <div className="flex flex-col items-center justify-center pt-5 pb-6">
                                        <div className="p-4 bg-orange-100 dark:bg-orange-900/30 text-orange-600 rounded-full mb-4 group-hover:scale-110 transition-transform">
                                            <Upload size={32} />
                                        </div>
                                        <p className="mb-2 text-sm text-gray-500 dark:text-gray-400">
                                            <span className="font-semibold text-orange-500">Click to upload</span> or drag and drop
                                        </p>
                                        <p className="text-xs text-gray-400">PNG, JPG or JPEG (MAX. 5MB)</p>
                                    </div>
                                    <input type="file" className="hidden" accept="image/*" onChange={handleImageChange} />
                                </label>
                            )}
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        {/* Ingredients */}
                        <div className="space-y-4">
                            <div className="flex items-center justify-between">
                                <label className="text-sm font-semibold text-gray-700 dark:text-gray-300 uppercase tracking-wider flex items-center gap-2">
                                    <Layers size={18} className="text-orange-500" />
                                    Ingredients
                                </label>
                                <button
                                    type="button"
                                    onClick={addIngredient}
                                    className="p-1 text-orange-500 hover:bg-orange-50 dark:hover:bg-orange-900/20 rounded-lg transition-colors"
                                >
                                    <Plus size={20} />
                                </button>
                            </div>
                            <div className="space-y-3">
                                {ingredients.map((ing, index) => (
                                    <div key={index} className="flex gap-2 group">
                                        <input
                                            type="text"
                                            value={ing}
                                            onChange={(e) => updateIngredient(index, e.target.value)}
                                            placeholder={`Ingredient ${index + 1}`}
                                            className="grow px-4 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-1 focus:ring-orange-500 outline-none dark:text-white"
                                        />
                                        <button
                                            type="button"
                                            onClick={() => removeIngredient(index)}
                                            className="p-2 text-gray-400 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-all"
                                        >
                                            <X size={18} />
                                        </button>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Instructions */}
                        <div className="space-y-4">
                            <div className="flex items-center justify-between">
                                <label className="text-sm font-semibold text-gray-700 dark:text-gray-300 uppercase tracking-wider flex items-center gap-2">
                                    <FileText size={18} className="text-orange-500" />
                                    Preparation Steps
                                </label>
                                <button
                                    type="button"
                                    onClick={addInstruction}
                                    className="p-1 text-orange-500 hover:bg-orange-50 dark:hover:bg-orange-900/20 rounded-lg transition-colors"
                                >
                                    <Plus size={20} />
                                </button>
                            </div>
                            <div className="space-y-3">
                                {instructions.map((step, index) => (
                                    <div key={index} className="flex gap-2 group">
                                        <div className="flex items-center justify-center w-8 h-8 rounded-full bg-orange-100 dark:bg-orange-900 text-orange-600 text-xs font-bold shrink-0 mt-1">
                                            {index + 1}
                                        </div>
                                        <textarea
                                            value={step}
                                            onChange={(e) => updateInstruction(index, e.target.value)}
                                            placeholder={`Step ${index + 1}`}
                                            rows="1"
                                            className="grow px-4 py-2 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-1 focus:ring-orange-500 outline-none dark:text-white resize-none"
                                        />
                                        <button
                                            type="button"
                                            onClick={() => removeInstruction(index)}
                                            className="p-2 text-gray-400 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-all"
                                        >
                                            <X size={18} />
                                        </button>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Visibility */}
                    <div className="flex items-center gap-4 p-6 bg-orange-50 dark:bg-orange-900/10 rounded-2xl border border-orange-100 dark:border-orange-900/20">
                        <div className="grow">
                            <h3 className="font-semibold text-orange-900 dark:text-orange-200">Public Recipe</h3>
                            <p className="text-sm text-orange-700 dark:text-orange-300">Allow other users to see and save your recipe.</p>
                        </div>
                        <label className="relative inline-flex items-center cursor-pointer">
                            <input
                                type="checkbox"
                                checked={isPublic}
                                onChange={() => setIsPublic(!isPublic)}
                                className="sr-only peer"
                            />
                            <div className="w-14 h-7 bg-gray-200 peer-focus:outline-none rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[4px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-6 after:w-6 after:transition-all peer-checked:bg-orange-600"></div>
                        </label>
                    </div>

                    {/* Submit */}
                    <div className="pt-6">
                        <button
                            type="submit"
                            disabled={loading}
                            className="w-full bg-gradient-to-r from-orange-500 to-red-600 hover:from-orange-600 hover:to-red-700 text-white font-bold py-4 rounded-2xl shadow-xl shadow-orange-500/20 flex items-center justify-center gap-2 transition-all transform hover:scale-[1.02] active:scale-[0.98] disabled:opacity-70"
                        >
                            {loading ? (
                                <>
                                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                    Creating...
                                </>
                            ) : (
                                <>
                                    <Save size={20} />
                                    Save Recipe
                                </>
                            )}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default CreateRecipe;
